### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by PeterHeja** [simonyiszk/matrix4-fw#1]
https://github.com/simonyiszk/matrix4-fw/blob/0efc30cf8ec99bc028946bd69225a905148b1276/Inc/version.hpp#L12

**Comment by kissadamfkut** [comment]
Fixed in commit 47b25da92072c851b2d02d0e19f8653f3b0fc89c

https://github.com/simonyiszk/matrix4-fw/commit/47b25da92072c851b2d02d0e19f8653f3b0fc89c
